name: Workflow Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    # Garante que o build rode em tipos específicos de eventos de PR
    types: [opened, synchronize, reopened]

  # Permite disparar manualmente pela aba Actions do GitHub
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Adicionando permissões mínimas de segurança
    permissions:
      contents: read

    env:
      SERVER_PORT: 8080
      DB_HOST: 127.0.0.1 # Mudança de localhost para 127.0.0.1 costuma ser mais estável em containers
      DB_PORT: 3306
      DB_NAME: grotrack
      DB_USERNAME: root
      DB_PASSWORD: 123456
      JWT_VALIDITY: 3600000
      JWT_SECRET: "RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdW..."

    services:
      mysql:
        image: henriquedandrade/bd-grotrack-v2:bd
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: grotrack
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Executar Build e Testes com Maven
        # clean verify roda testes unitários e de integração
        run: mvn clean verify

      - name: Upload do Relatório de Cobertura JaCoCo
        # O 'if: always()' garante que o relatório suba mesmo se os testes falharem
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 7 # Opcional: limpa o storage do GitHub após uma semana