name: Workflow Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    env:
      SERVER_PORT: 8080
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: grotrack
      DB_USERNAME: root
      DB_PASSWORD: 123456
      JWT_VALIDITY: 3600000
      JWT_SECRET: "RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdW..."

    services:
      mysql:
        image: henriquedandrade/bd-grotrack-v2:bd
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: grotrack
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para o SonarQube analisar o hist贸rico de commits

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Dependency Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn org.owasp:dependency-check-maven:check -DnvdApiKey=$NVD_API_KEY

      - name: Executar Build e Testes com Maven (JaCoCo)
        # O verify garante que o JaCoCo gere o relat贸rio xml antes do Sonar rodar
        run: mvn clean verify -DskipTests=false

      - name: Executar SonarQube Scan
        if: always() # Garante que o scan rode mesmo se um teste falhar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn sonar:sonar 
          -Dsonar.projectKey=grotrack 
          -Dsonar.organization=grotrack 
          -Dsonar.host.url=https://sonarcloud.io

      - name: Upload do Relat贸rio de Cobertura JaCoCo
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 7